# Day 1 

In [3]:
import pandas as pd 
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 
df = pd.DataFrame(data) 
df["Name"]= df["Name"].str.lower()
df['Qualification'] = df['Qualification'].str.lower()
df

Name  Age    Address Qualification
0     jai   27      Delhi           msc
1  princi   24     Kanpur            ma
2  gaurav   22  Allahabad           mca
3    anuj   32    Kannauj           phd

In [5]:
import pandas as pd 
     
# Define a dictionary containing employee data 
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Knnuaj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 
 
# Convert the dictionary into DataFrame  
df = pd.DataFrame(data) 
    
# dropping null value columns to avoid errors 
df.dropna(inplace = True) 
    
# new data frame with split value columns 
df["Address"]= df["Address"].str.split("a", n = 1, expand = True)[0] 
df

Name  Age Address Qualification
0     Jai   27       N           Msc
1  Princi   24       K            MA
2  Gaurav   22     All           MCA
3    Anuj   32    Knnu           Phd

In [12]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 
df = pd.DataFrame(data) 
new = df["Address"].copy() 
df["Name"].str.cat(new, sep =", ") 

0          Jai, Nagpur
1       Princi, Kanpur
2    Gaurav, Allahabad
3        Anuj, Kannuaj
Name: Name, dtype: object

In [13]:
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'], 
        'Age':[27, 24, 22, 32], 
        'Address':['Nagpur junction', 'Kanpur junction', 
                   'Nagpur junction', 'Kannuaj junction'], 
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']} 
 
# Convert the dictionary into DataFrame  
df = pd.DataFrame(data)
   
# replacing address name and adding spaces in start and end 
new = df["Address"].replace("Nagpur junction", "  Nagpur junction  ").copy() 
   
# checking with custom string 
print(new.str.strip()==" Nagpur junction")
print(new.str.strip()=="Nagpur junction ")
print(new.str.strip()==" Nagpur junction ")

0    False
1    False
2    False
3    False
Name: Address, dtype: bool
0    False
1    False
2    False
3    False
Name: Address, dtype: bool
0    False
1    False
2    False
3    False
Name: Address, dtype: bool


In [19]:
# checking with custom removed space string 
new.str.lstrip()=="Boston Celtics  "
new.str.rstrip()=="     Boston Celtics  "
new.str.strip()=="      Boston Celtics       "

0    False
1    False
2    False
3    False
Name: Address, dtype: bool

In [21]:
s = pd.Series(['a1', 'b2', 'c3'])
 
# Extracting a data
n= s.str.extract(r'([ab])(\d)')
n

0    1
0    a    1
1    b    2
2  NaN  NaN

In [23]:
s = pd.Series(['a1', 'b2', 'c3'])
 
# Extracting a data
n= s.str.extract(r'([a-z])')
n

0
0  a
1  b
2  c

In [25]:
s = pd.Series(['a1', 'b2', 'c3'])
 
# Extracting a data
n= s.str.extract(r'(\d)')
n

0
0  1
1  2
2  3

In [26]:
s = pd.Series(['a1', 'b2', 'c3'])
 
# Extracting a data
n = s.str.extract(r'(?P<Geeks>[ab])(?P<For>\d)')
n

Geeks  For
0     a    1
1     b    2
2   NaN  NaN

# Day 2

In [27]:
import pandas as pd
  
# making data frame from csv file
data = pd.read_csv("employees.csv")
  
# converting and overwriting values in column
data["First Name"]= data["First Name"].str.lower()
  
# display
data

First Name  Gender  Start Date Last Login Time  Salary  Bonus %  \
0      douglas    Male    8/6/1993        12:42 PM   97308    6.945   
1       thomas    Male   3/31/1996         6:53 AM   61933    4.170   
2        maria  Female   4/23/1993        11:17 AM  130590   11.858   
3        jerry    Male    3/4/2005         1:00 PM  138705    9.340   
4        larry    Male   1/24/1998         4:47 PM  101004    1.389   
..         ...     ...         ...             ...     ...      ...   
995      henry     NaN  11/23/2014         6:09 AM  132483   16.655   
996    phillip    Male   1/31/1984         6:30 AM   42392   19.675   
997    russell    Male   5/20/2013        12:39 PM   96914    1.421   
998      larry    Male   4/20/2013         4:45 PM   60500   11.985   
999     albert    Male   5/15/2012         6:24 PM  129949   10.169   

    Senior Management                  Team  
0                True             Marketing  
1                True                   NaN  
2               False               Finance  
3                True               Finance  
4                True       Client Services  
..                ...                   ...  
995             False          Distribution  
996             False               Finance  
997             False               Product  
998             False  Business Development  
999              True                 Sales  

[1000 rows x 8 columns]

In [32]:
data["Team"]= data["Team"].str.upper()
data["Team"]

0                 MARKETING
1                       NaN
2                   FINANCE
3                   FINANCE
4           CLIENT SERVICES
               ...         
995            DISTRIBUTION
996                 FINANCE
997                 PRODUCT
998    BUSINESS DEVELOPMENT
999                   SALES
Name: Team, Length: 1000, dtype: object

In [33]:
data["Team"]= data["Team"].str.upper().str.title()
data["Team"]

0                 Marketing
1                       NaN
2                   Finance
3                   Finance
4           Client Services
               ...         
995            Distribution
996                 Finance
997                 Product
998    Business Development
999                   Sales
Name: Team, Length: 1000, dtype: object

# day 3

In [34]:
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")
 
# overwriting column with replaced value of age
data["Age"]= data["Age"].replace(25.0, "Twenty five")
 
# creating a filter for age column
# where age = "Twenty five"
filter = data["Age"]=="Twenty five"
 
# printing only filtered columns
data.where(filter).dropna()

Name                    Team  Number Position  \
0          Avery Bradley          Boston Celtics     0.0       PG   
1            Jae Crowder          Boston Celtics    99.0       SF   
7           Kelly Olynyk          Boston Celtics    41.0        C   
26       Thomas Robinson           Brooklyn Nets    41.0       PF   
35      Cleanthony Early         New York Knicks    11.0       SF   
44      Derrick Williams         New York Knicks    23.0       PF   
47         Isaiah Canaan      Philadelphia 76ers     0.0       PG   
48      Robert Covington      Philadelphia 76ers    33.0       SF   
59       Hollis Thompson      Philadelphia 76ers    31.0       SG   
71         Terrence Ross         Toronto Raptors    31.0       SF   
79             Ian Clark   Golden State Warriors    21.0       SG   
105          C.J. Wilcox    Los Angeles Clippers    30.0       SG   
113           Ryan Kelly      Los Angeles Lakers     4.0       PF   
126         John Jenkins            Phoenix Suns    23.0       SG   
130         Phil Pressey            Phoenix Suns    25.0       PG   
136           Quincy Acy        Sacramento Kings    13.0       SF   
143     DeMarcus Cousins        Sacramento Kings    15.0        C   
144           Seth Curry        Sacramento Kings    30.0       SG   
151     Cameron Bairstow           Chicago Bulls    41.0       PF   
166  Matthew Dellavedova     Cleveland Cavaliers     8.0       PG   
175         Jordan McRae     Cleveland Cavaliers    12.0       SG   
177        Iman Shumpert     Cleveland Cavaliers     4.0       SG   
179     Tristan Thompson     Cleveland Cavaliers    13.0        C   
184        Lorenzo Brown         Detroit Pistons    17.0       PG   
185       Reggie Bullock         Detroit Pistons    25.0       SF   
202         Solomon Hill          Indiana Pacers    44.0       SF   
209   Shayne Whittington          Indiana Pacers    42.0       PF   
214     Jared Cunningham         Milwaukee Bucks     9.0       SG   
216          John Henson         Milwaukee Bucks    31.0       PF   
266       JaMychal Green       Memphis Grizzlies     0.0       PF   
272     Lance Stephenson       Memphis Grizzlies     1.0       SF   
284          James Ennis    New Orleans Pelicans     4.0       SF   
286          Tim Frazier    New Orleans Pelicans     2.0       PG   
289      Jordan Hamilton    New Orleans Pelicans    25.0       SG   
290         Jrue Holiday    New Orleans Pelicans    11.0       PG   
366       Nikola Vucevic           Orlando Magic     9.0        C   
382            John Wall      Washington Wizards     2.0       PG   
385          Will Barton          Denver Nuggets     5.0       SF   
404        Adreian Payne  Minnesota Timberwolves    33.0       PF   
428      Al-Farouq Aminu  Portland Trail Blazers     8.0       SF   
436       Damian Lillard  Portland Trail Blazers     0.0       PG   

             Age Height  Weight               College      Salary  
0    Twenty five    6-2   180.0                 Texas   7730337.0  
1    Twenty five    6-6   235.0             Marquette   6796117.0  
7    Twenty five    7-0   238.0               Gonzaga   2165160.0  
26   Twenty five   6-10   237.0                Kansas    981348.0  
35   Twenty five    6-8   210.0         Wichita State    845059.0  
44   Twenty five    6-8   240.0               Arizona   4000000.0  
47   Twenty five    6-0   201.0          Murray State    947276.0  
48   Twenty five    6-9   215.0       Tennessee State   1000000.0  
59   Twenty five    6-8   206.0            Georgetown    947276.0  
71   Twenty five    6-7   195.0            Washington   3553917.0  
79   Twenty five    6-3   175.0               Belmont    947276.0  
105  Twenty five    6-5   195.0            Washington   1159680.0  
113  Twenty five   6-11   230.0                  Duke   1724250.0  
126  Twenty five    6-4   215.0            Vanderbilt    981348.0  
130  Twenty five   5-11   175.0              Missouri     55722.0  
136  Twenty five    6-7   240.0  

In [36]:
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")
 
# overwriting column with replaced value of age
data["Team"]= data["Team"].str.replace("boston", "New Boston", case = False)
 
# creating a filter for age column
# where age = "Twenty five"
filter = data["Team"]=="New Boston Celtics"
 
# printing only filtered columns
data.where(filter).dropna()

Name                Team  Number Position   Age Height  Weight  \
0     Avery Bradley  New Boston Celtics     0.0       PG  25.0    6-2   180.0   
1       Jae Crowder  New Boston Celtics    99.0       SF  25.0    6-6   235.0   
3       R.J. Hunter  New Boston Celtics    28.0       SG  22.0    6-5   185.0   
6     Jordan Mickey  New Boston Celtics    55.0       PF  21.0    6-8   235.0   
7      Kelly Olynyk  New Boston Celtics    41.0        C  25.0    7-0   238.0   
8      Terry Rozier  New Boston Celtics    12.0       PG  22.0    6-2   190.0   
9      Marcus Smart  New Boston Celtics    36.0       PG  22.0    6-4   220.0   
10  Jared Sullinger  New Boston Celtics     7.0        C  24.0    6-9   260.0   
11    Isaiah Thomas  New Boston Celtics     4.0       PG  27.0    5-9   185.0   
12      Evan Turner  New Boston Celtics    11.0       SG  27.0    6-7   220.0   
13      James Young  New Boston Celtics    13.0       SG  20.0    6-6   215.0   
14     Tyler Zeller  New Boston Celtics    44.0        C  26.0    7-0   253.0   

           College     Salary  
0            Texas  7730337.0  
1        Marquette  6796117.0  
3    Georgia State  1148640.0  
6              LSU  1170960.0  
7          Gonzaga  2165160.0  
8       Louisville  1824360.0  
9   Oklahoma State  3431040.0  
10      Ohio State  2569260.0  
11      Washington  6912869.0  
12      Ohio State  3425510.0  
13        Kentucky  1749840.0  
14  North Carolina  2616975.0

In [39]:
filter = data["Position"]=="C"
 
# printing only filtered columns
data.where(filter).dropna()

Name                    Team  Number Position   Age  \
7           Kelly Olynyk      New Boston Celtics    41.0        C  25.0   
10       Jared Sullinger      New Boston Celtics     7.0        C  24.0   
14          Tyler Zeller      New Boston Celtics    44.0        C  26.0   
23           Brook Lopez           Brooklyn Nets    11.0        C  28.0   
27            Henry Sims           Brooklyn Nets    14.0        C  26.0   
38           Robin Lopez         New York Knicks     8.0        C  28.0   
49           Joel Embiid      Philadelphia 76ers    21.0        C  22.0   
56         Jahlil Okafor      Philadelphia 76ers     8.0        C  20.0   
78          Andrew Bogut   Golden State Warriors    12.0        C  31.0   
81          Festus Ezeli   Golden State Warriors    31.0        C  26.0   
88     Marreese Speights   Golden State Warriors     5.0        C  28.0   
91          Cole Aldrich    Los Angeles Clippers    45.0        C  27.0   
98        DeAndre Jordan    Los Angeles Clippers     6.0        C  27.0   
107          Tarik Black      Los Angeles Lakers    28.0        C  24.0   
111          Roy Hibbert      Los Angeles Lakers    17.0        C  29.0   
117         Robert Sacre      Los Angeles Lakers    50.0        C  27.0   
128             Alex Len            Phoenix Suns    21.0        C  22.0   
135        Alan Williams            Phoenix Suns    15.0        C  23.0   
141  Willie Cauley-Stein        Sacramento Kings     0.0        C  22.0   
143     DeMarcus Cousins        Sacramento Kings    15.0        C  25.0   
147         Kosta Koufos        Sacramento Kings    41.0        C  27.0   
162          Joakim Noah           Chicago Bulls    13.0        C  31.0   
173           Sasha Kaun     Cleveland Cavaliers    14.0        C  31.0   
179     Tristan Thompson     Cleveland Cavaliers    13.0        C  25.0   
181         Joel Anthony         Detroit Pistons    50.0        C  33.0   
182          Aron Baynes         Detroit Pistons    12.0        C  29.0   
188       Andre Drummond         Detroit Pistons     0.0        C  22.0   
201          Jordan Hill          Indiana Pacers    27.0        C  28.0   
220          Greg Monroe         Milwaukee Bucks    15.0        C  26.0   
224        Miles Plumlee         Milwaukee Bucks    18.0        C  27.0   
234         JaVale McGee        Dallas Mavericks    11.0        C  28.0   
296          Matt Bonner       San Antonio Spurs    15.0        C  36.0   
298           Tim Duncan       San Antonio Spurs    21.0        C  40.0   
312           Al Horford           Atlanta Hawks    15.0        C  30.0   
331   Frank Kaminsky III       Charlotte Hornets    44.0        C  23.0   
338          Cody Zeller       Charlotte Hornets    40.0        C  23.0   
351     Hassan Whiteside              Miami Heat    21.0        C  26.0   
354       Dewayne Dedmon           Orlando Magic     3.0        C  26.0   
366       Nikola Vucevic           Orlando Magic     9.0        C  25.0   
374           JJ Hickson      Washington Wizards    21.0        C  27.0   
399         Gorgui Dieng  Minnesota Timberwolves     5.0        C  26.0   
410   Karl-Anthony Towns  Minnesota Timberwolves    32.0        C  20.0   
412         Steven Adams   Oklahoma City Thunder    12.0        C  22.0   
418          Enes Kanter   Oklahoma City Thunder    11.0        C  24.0   
420        Nazr Mohammed   Oklahoma City Thunder    13.0        C  38.0   
431             Ed Davis  Portland Trail Blazers    17.0        C  27.0   
434          Chris Kaman  Portland Trail Blazers    35.0        C  34.0   
439        Mason Plumlee  Portland Trail Blazers    24.0        C  26.0   
456          Jeff Withey               Utah Jazz    24.0        C  26.0   

    Height  Weight               College      Salary  
7      7-0   238.0               Gonzaga   2165160.0  
10     6-9   260.0            Ohio State   2569260.0  
14     7-0   253.0        North Carolina   2616975.0  
23     7-0   275.0              Stanford  1968900

In [40]:
filter = data["Position"]=="PG"
 
# printing only filtered columns
data.where(filter).dropna()

Name                    Team  Number Position   Age Height  \
0        Avery Bradley      New Boston Celtics     0.0       PG  25.0    6-2   
8         Terry Rozier      New Boston Celtics    12.0       PG  22.0    6-2   
9         Marcus Smart      New Boston Celtics    36.0       PG  22.0    6-4   
11       Isaiah Thomas      New Boston Celtics     4.0       PG  27.0    5-9   
19        Jarrett Jack           Brooklyn Nets     2.0       PG  32.0    6-3   
..                 ...                     ...     ...      ...   ...    ...   
426  Russell Westbrook   Oklahoma City Thunder     0.0       PG  27.0    6-3   
436     Damian Lillard  Portland Trail Blazers     0.0       PG  25.0    6-3   
440      Brian Roberts  Portland Trail Blazers     2.0       PG  30.0    6-1   
443         Trey Burke               Utah Jazz     3.0       PG  23.0    6-1   
453       Shelvin Mack               Utah Jazz     8.0       PG  26.0    6-3   

     Weight         College      Salary  
0     180.0           Texas   7730337.0  
8     190.0      Louisville   1824360.0  
9     220.0  Oklahoma State   3431040.0  
11    185.0      Washington   6912869.0  
19    200.0    Georgia Tech   6300000.0  
..      ...             ...         ...  
426   200.0            UCLA  16744218.0  
436   195.0     Weber State   4236287.0  
440   173.0          Dayton   2854940.0  
443   191.0        Michigan   2658240.0  
453   203.0          Butler   2433333.0  

[76 rows x 9 columns]

# Day 4

In [46]:
sr = pd.Series([10, 25, 3, 11, 24, 6])
  
# Create the Index
idx = ['Coca Cola', 'Sprite', 'Coke', 'Fanta', 'Dew', 'ThumbsUp']
sr.index = idx
sr

Coca Cola    10
Sprite       25
Coke          3
Fanta        11
Dew          24
ThumbsUp      6
dtype: int64

In [47]:
result = sr.replace(to_replace = 3, value = 1000)
result

Coca Cola      10
Sprite         25
Coke         1000
Fanta          11
Dew            24
ThumbsUp        6
dtype: int64

In [48]:
sr = pd.Series(['New York', 'Chicago', 'Toronto', 'Lisbon', 'Rio'])
  
# Create the Index
index_ = ['City 1', 'City 2', 'City 3', 'City 4', 'City 5'] 
  
# set the index
sr.index = index_
sr

City 1    New York
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5         Rio
dtype: object

In [51]:
result = sr.replace(to_replace = ['New York', 'Rio'],
                    value = ['London', 'Brisbane'])
result

City 1      London
City 2     Chicago
City 3     Toronto
City 4      Lisbon
City 5    Brisbane
dtype: object

In [52]:
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")
  
# replacing team name and adding spaces in start and end
new = data["Team"].replace("Boston Celtics", "  Boston Celtics  ").copy()
  
# checking with custom removed space string
new.str.lstrip()=="Boston Celtics  "

0       True
1       True
2       True
3       True
4       True
       ...  
453    False
454    False
455    False
456    False
457    False
Name: Team, Length: 458, dtype: bool

In [53]:
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")
  
# replacing team name and adding spaces in start and end
new = data["Team"].replace("Boston Celtics", "  Boston Celtics  ").copy()
  
# checking with custom string
new.str.strip()=="  Boston Celtic"
new.str.strip()=="Boston Celtics  "
new.str.strip()=="  Boston Celtic  "

0      False
1      False
2      False
3      False
4      False
       ...  
453    False
454    False
455    False
456    False
457    False
Name: Team, Length: 458, dtype: bool

In [54]:
data = pd.read_csv("https://media.geeksforgeeks.org/wp-content/uploads/nba.csv")
  
# replacing team name and adding spaces in start and end
new = data["Team"].replace("Boston Celtics", "  Boston Celtics  ").copy()
  
# checking with custom removed space string
new.str.rstrip()=="  Boston Celtics"

0       True
1       True
2       True
3       True
4       True
       ...  
453    False
454    False
455    False
456    False
457    False
Name: Team, Length: 458, dtype: bool

In [56]:
import pandas as pd
ts = pd.Timestamp('2021-07-08 07:15:11')
 
# Create the DateOffset
do = pd.tseries.offsets.DateOffset(n = 2)
 
# Print the Timestamp
print(ts)
do

2021-07-08 07:15:11


<2 * DateOffsets>

In [57]:
new_timestamp = ts + do
 
# Print the updated timestamp
print(new_timestamp)

2021-07-10 07:15:11


In [58]:
ts = pd.Timestamp('2021-10-10 07:15:11')
 
# Create the DateOffset
do = pd.tseries.offsets.DateOffset(days = 10, hours = 2)
 
# Print the Timestamp
print(ts)
 
# Print the DateOffset
print(do)

2021-10-10 07:15:11
<DateOffset: days=10, hours=2>


In [59]:
new_timestamp = ts + do
 
# Print the updated timestamp
print(new_timestamp)

2021-10-20 09:15:11


# Day 4

In [61]:
lst = ['Geeks', 'For', 'Geeks', 'is', 
            'portal', 'for', 'Geeks']
 
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
df

0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [63]:
import pandas as pd
 
# intialise data of lists.
data = {'Name':['Tom', 'nick', 'krish', 'jack'],
        'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [64]:
import pandas as pd
 
# Define a dictionary containing employee data
data = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Address':['Delhi', 'Kanpur', 'Allahabad', 'Kannauj'],
        'Qualification':['Msc', 'MA', 'MCA', 'Phd']}
 
# Convert the dictionary into DataFrame 
df = pd.DataFrame(data)
df

Name  Age    Address Qualification
0     Jai   27      Delhi           Msc
1  Princi   24     Kanpur            MA
2  Gaurav   22  Allahabad           MCA
3    Anuj   32    Kannauj           Phd

In [68]:
### we can get value of whole row by iloc method
data = pd.read_csv("nba.csv", index_col ="Name")
data

Team  Number Position   Age Height  Weight  \
Name                                                                  
Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0   
Jae Crowder    Boston Celtics    99.0       SF  25.0    6-6   235.0   
John Holland   Boston Celtics    30.0       SG  27.0    6-5   205.0   
R.J. Hunter    Boston Celtics    28.0       SG  22.0    6-5   185.0   
Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0   
...                       ...     ...      ...   ...    ...     ...   
Shelvin Mack        Utah Jazz     8.0       PG  26.0    6-3   203.0   
Raul Neto           Utah Jazz    25.0       PG  24.0    6-1   179.0   
Tibor Pleiss        Utah Jazz    21.0        C  26.0    7-3   256.0   
Jeff Withey         Utah Jazz    24.0        C  26.0    7-0   231.0   
NaN                       NaN     NaN      NaN   NaN    NaN     NaN   

                         College     Salary  
Name                                         
Avery Bradley              Texas  7730337.0  
Jae Crowder            Marquette  6796117.0  
John Holland   Boston University        NaN  
R.J. Hunter        Georgia State  1148640.0  
Jonas Jerebko                NaN  5000000.0  
...                          ...        ...  
Shelvin Mack              Butler  2433333.0  
Raul Neto                    NaN   900000.0  
Tibor Pleiss                 NaN  2900000.0  
Jeff Withey               Kansas   947276.0  
NaN                          NaN        NaN  

[458 rows x 8 columns]

In [69]:
# retrieving row by loc method
first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
 
 
print(first, "\n\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


In [70]:
data = pd.read_csv("nba.csv", index_col ="Name")
 
# retrieving columns by indexing operator
first = data["Age"]
first

Name
Avery Bradley    25.0
Jae Crowder      25.0
John Holland     27.0
R.J. Hunter      22.0
Jonas Jerebko    29.0
                 ... 
Shelvin Mack     26.0
Raul Neto        24.0
Tibor Pleiss     26.0
Jeff Withey      26.0
NaN               NaN
Name: Age, Length: 458, dtype: float64

In [72]:
data = pd.read_csv("nba.csv", index_col ="Name")

first = data.loc["Avery Bradley"]
second = data.loc["R.J. Hunter"]
 
 
print(first, "\n\n\n", second)

Team        Boston Celtics
Number                 0.0
Position                PG
Age                   25.0
Height                 6-2
Weight               180.0
College              Texas
Salary           7730337.0
Name: Avery Bradley, dtype: object 


 Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object


In [73]:
data.iloc[3] 

Team        Boston Celtics
Number                28.0
Position                SG
Age                   22.0
Height                 6-5
Weight               185.0
College      Georgia State
Salary           1148640.0
Name: R.J. Hunter, dtype: object

In [75]:
import numpy as np
 
# dictionary of lists
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, 45, 56, np.nan],
        'Third Score':[np.nan, 40, 80, 98]}
 
# creating a dataframe from list
df = pd.DataFrame(dict)
 
# using isnull() function  
df

First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          45.0         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [76]:
df.isnull()

First Score  Second Score  Third Score
0        False         False         True
1        False         False        False
2         True         False        False
3        False          True        False

In [77]:
df.fillna(0)

First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0          45.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [78]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
   
df

First Score  Second Score  Third Score  Fourth Score
0        100.0          30.0           52           NaN
1         90.0           NaN           40           NaN
2          NaN          45.0           80           NaN
3         95.0          56.0           98          65.0

In [79]:
dict = {'First Score':[100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 45, 56],
        'Third Score':[52, 40, 80, 98],
        'Fourth Score':[np.nan, np.nan, np.nan, 65]}
 
# creating a dataframe from dictionary
df = pd.DataFrame(dict)
 
# using dropna() function  
df.dropna()

First Score  Second Score  Third Score  Fourth Score
3         95.0          56.0           98          65.0

In [80]:
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
# creating a dataframe from a dictionary 
df = pd.DataFrame(dict)
df

name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [81]:
for i, j in df.iterrows():
    print(i, j)
    print()

0 name      aparna
degree       MBA
score         90
Name: 0, dtype: object

1 name      pankaj
degree       BCA
score         40
Name: 1, dtype: object

2 name      sudhir
degree    M.Tech
score         80
Name: 2, dtype: object

3 name      Geeku
degree      MBA
score        98
Name: 3, dtype: object



In [82]:
# creating a list of dataframe columns
columns = list(df)
 
for i in columns:
    print (df[i][2])

sudhir
M.Tech
80


In [83]:
import pandas as pd
 
# Calling DataFrame constructor
df = pd.DataFrame()
df

Empty DataFrame
Columns: []
Index: []

In [84]:
lst = ['Geeks', 'For', 'Geeks', 'is',
            'portal', 'for', 'Geeks']
 
# Calling DataFrame constructor on list
df = pd.DataFrame(lst)
df

0
0   Geeks
1     For
2   Geeks
3      is
4  portal
5     for
6   Geeks

In [85]:
data = {'Name':['Tom', 'nick', 'krish', 'jack'], 'Age':[20, 21, 19, 18]}
 
# Create DataFrame
df = pd.DataFrame(data)
df

Name  Age
0    Tom   20
1   nick   21
2  krish   19
3   jack   18

In [86]:
dict = {'name':["aparna", "pankaj", "sudhir", "Geeku"],
        'degree': ["MBA", "BCA", "M.Tech", "MBA"],
        'score':[90, 40, 80, 98]}
 
df = pd.DataFrame(dict)
df

name  degree  score
0  aparna     MBA     90
1  pankaj     BCA     40
2  sudhir  M.Tech     80
3   Geeku     MBA     98

In [87]:
import pandas as pd
 
# simple array
data = [1, 2, 3, 4]
 
ser = pd.Series(data)
ser

0    1
1    2
2    3
3    4
dtype: int64

In [88]:
import pandas as pd
 
# Creating empty series
ser = pd.Series()
ser

Series([], dtype: object)

In [89]:
data = np.array(['g', 'e', 'e', 'k', 's'])
ser = pd.Series(data)
ser

0    g
1    e
2    e
3    k
4    s
dtype: object

In [90]:
ser = pd.Series(data, index=[10, 11, 12, 13, 14])
ser

10    g
11    e
12    e
13    k
14    s
dtype: object

In [91]:
list = ['g', 'e', 'e', 'k', 's']
 
# create series form a list
ser = pd.Series(list)
print(ser)

0    g
1    e
2    e
3    k
4    s
dtype: object


In [92]:
dict = {'Geeks': 10,
        'for': 20,
        'geeks': 30}
 
# create series from dictionary
ser = pd.Series(dict)
ser

Geeks    10
for      20
geeks    30
dtype: int64

In [93]:
ser = pd.Series(10, index=[0, 1, 2, 3, 4, 5])
ser

0    10
1    10
2    10
3    10
4    10
5    10
dtype: int64

In [95]:
ser1 = pd.Series(np.linspace(3, 33, 3))
print(ser1)
 
# series with numpy linspace()
ser2 = pd.Series(np.linspace(1, 100, 10))
print(ser2)

0     3.0
1    18.0
2    33.0
dtype: float64
0      1.0
1     12.0
2     23.0
3     34.0
4     45.0
5     56.0
6     67.0
7     78.0
8     89.0
9    100.0
dtype: float64


In [96]:
import pandas as pd
ser=pd.Series(range(10))
print(ser)

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int64


In [97]:
ser=pd.Series(range(1,20,3), index=[x for x in 'abcdefg'])
print(ser)

a     1
b     4
c     7
d    10
e    13
f    16
g    19
dtype: int64


In [105]:
ser=np.arange(10,15)
serobj=pd.Series(data=ser*5,index=ser)
print(serobj)

10    50
11    55
12    60
13    65
14    70
dtype: int32


In [106]:
np.arange(10,15)

array([10, 11, 12, 13, 14])

# Day 5

### inverse of matrix

In [6]:
#importing NumPy library
import  numpy as np
 
#importing SciPy library
from scipy import linalg
# 2 x 2
A = [[1,2],[1,4]]

linalg.inv(A)

array([[ 2. , -1. ],
       [-0.5,  0.5]])

In [7]:
# 3 x 3
A = [[2,1,2],[1,1,4],[1,1,6]]

linalg.inv(A)

array([[ 1. , -2. ,  1. ],
       [-1. ,  5. , -3. ],
       [ 0. , -0.5,  0.5]])

### Determinant

In [11]:
A = [[45,9],[66,10]]
linalg.det(A)

-144.00000000000003

In [12]:
A = [[11,22,32],[25,27,14],[23,21,19]]

linalg.det(A)

-4028.999999999999

### Norm

In [10]:
A = [[11,22,32],[25,27,14],[23,21,19]]
B = [[4,3,2],[4,13,5],[21,11,22]]

In [14]:
np.dot(A,B)

array([[804, 671, 836],
       [502, 580, 493],
       [575, 551, 569]])

In [13]:
linalg.norm(np.dot(A,B))

1893.4077743581809

### Factorial of a list

In [16]:
#importing NumPy library
import numpy as np
#importing SciPy library
from scipy.special import factorial

In [15]:
list1 = [1,1,1,1,1]

In [18]:
factorial(sum(list1))

120.0

In [21]:
list1 = [1,1,2,1,1]
factorial(sum(list1))

720.0

###  Calculate the gravitational force

In [22]:
m1,m2,r = (12,10,7)

In [25]:
from scipy.constants import G
 
def gravitational_force(m1,m2,r):
    F=(G*m1*m2)/(r**2)
    print(F)
gravitational_force(m1,m2,r)

1.6345224489795917e-10


In [26]:
m1,m2,r = (100,150,10)
gravitational_force(m1,m2,r)

1.001145e-08


###  Area of the circle

In [30]:
import scipy
from scipy.constants import pi

N = 12

def circular_area(N):
    return pi* ((N/2)**2)
circular_area(N)

113.09733552923255

In [32]:
N = 11
circular_area(N)

95.03317777109125

### cubic root
- Consider a list as list1 containing integers as elements. Perform multiplication of all the even elements in the list and print the cube root of the multiplicative total.

In [45]:
#importing SciPy library
import scipy
from scipy.special import cbrt

list1= [1,2,3,4,5,6,7,8]

mul = 1 
for i in list1:
  if i %2==0:
    mul *= i
print(cbrt(mul))

7.268482371328559


In [46]:
list1= [1,2,1,2,2]
mul = 1 
for i in list1:
  if i %2==0:
    mul *= i
cbrt(mul)

2.0

### Log Sum Exponential of a list
- Compute and store all the prime numbers present within a range (X, Y) in a list. Now find and print the Log Sum Exponential using the list of prime numbers within the provided range.

In [14]:
from scipy.special import logsumexp

def isPrime(n):
    pl = []
    if n<=1: 
        return False
    else:
        for i in range(2,n):
            if n%i==0:
                pl.append(i)
            else:
                pass
    if pl==[]:
        return True
    else:
        return False




def logSumExpo(X,Y):
    fl=[] 
    for j in range(X,Y):
        if isPrime(j):
            fl.append(j)
        else:
            pass
    print(logsumexp(fl))
logSumExpo(0,100)

97.00033625289022


### reverse of string

In [14]:
str1 = list('Vivek')
str2 = ''
n = len(str1)

for i in range(0,int(n/2)):
    str1[i] , str1[n-i-1] = str1[n-i-1] , str1[i]

In [16]:
str1

['k', 'e', 'v', 'i', 'V']

In [26]:
import numpy as np
list1= np.array([1, 2, 3, 4, 5, 6])

print(np.flip(list1))

[6 5 4 3 2 1]


### All combinations of two Numpy arrays

In [63]:
array1 = [1, 2] 
array2 = [3, 4]
l1 = []

for i in array1:
    for j in array2:
        l1.append([i,j])
l1

[[1, 3], [1, 4], [2, 3], [2, 4]]

In [67]:
import numpy as np
print(np.meshgrid(array1 , array2))

[array([[1, 2],
       [1, 2]]), array([[3, 3],
       [4, 4]])]


In [70]:
print(np.array(np.meshgrid(array1,array2)).T.reshape(-1,2))

[[1 3]
 [1 4]
 [2 3]
 [2 4]]


In [81]:
array1= np.array([[5, 8, 6], [5, 1, 3], [2, 4, 5]])
array1.flatten()

array([5, 8, 6, 5, 1, 3, 2, 4, 5])

In [88]:
l = []
for i in array1:
    for j in i:
        l.append(j)
l

[5, 8, 6, 5, 1, 3, 2, 4, 5]

In [103]:
import numpy as np

matrix1 = [[1,0,9],
           [5,4,8]]

matrix2 = [[2,4,5],
           [1,1,1]]


c = []
for i in range(len(matrix1)):
  l2 = []
  for j in range(len(matrix1[i])):
    l2.append(matrix1[i][j]+matrix2[i][j])
  c.append(l2)
np.array(c).reshape(2,-1)

array([[ 3,  4, 14],
       [ 6,  5,  9]])

In [104]:
c

[[3, 4, 14], [6, 5, 9]]

In [105]:
print(matrix1+matrix2)

[[1, 0, 9], [5, 4, 8], [2, 4, 5], [1, 1, 1]]


In [107]:
matrix1 = np.array([[1, 0, 9],
[5, 4, 8]])

matrix2 = np.array([[2, 4, 5],
[1, 1, 1]])

result = matrix1 + matrix2
result.reshape(2, -1)

array([[ 3,  4, 14],
       [ 6,  5,  9]])

In [108]:
np.sum(matrix1 * matrix2)

64

In [119]:
import math
matrix1 = [[1, 2],
          [2, 3],
          [4,5]]
matrix2 = [[7, 5, 4],
          [6, 7, 5]]


    
# Get the number of rows and columns for each matrix
rows1, cols1 = len(matrix1), len(matrix1[0])
rows2, cols2 = len(matrix2), len(matrix2[0])

# Initialize the result matrix with zeros
result = [[0 for _ in range(cols2)] for _ in range(rows1)]

# Perform matrix multiplication
for i in range(rows1):
    for j in range(cols2):
        for k in range(cols1):
            result[i][j] += matrix1[i][k] * matrix2[k][j]
print(np.array(result).reshape(3,-1))

[[19 19 14]
 [32 31 23]
 [58 55 41]]


In [122]:
def reshape_list(lst, rows, cols):
    reshaped = []
    index = 0
    for _ in range(rows):
        row = []
        for _ in range(cols):
            row.append(lst[index])
            index += 1
        reshaped.append(row)

    return reshaped

reshaped_list = reshape_list(result, 1, 3)
print(reshaped_list)


[[[19, 19, 14], [32, 31, 23], [58, 55, 41]]]


### replacing values if values is > X

In [5]:
#importing Numpy package
import numpy as np
array1= [112.343, 123.35,  22.34]
X = 99
for i in range(len(array1)):
  if X > array1[i]:
    array1[i] = X
print(array1)

[112.343, 123.35, 99]


### replacing diagonal values

In [8]:
A = [[11,18,16],[12,22,11],[13,15,11]]
X =10

def replacingDiagonals(A,X):
    for i in range(len(A)):
        for j in range(len(A[i])):
            if i == j:
                A[i][j] = X
    print(A)
replacingDiagonals(A,X)

[[10, 18, 16], [12, 10, 11], [13, 15, 10]]


In [9]:
A

[[10, 18, 16], [12, 10, 11], [13, 15, 10]]

### get all indeces where element is zero

In [25]:
l = []
array1= [1, 2, 0, 10, 14, 1, 0]

for i in range(len(array1)):
  if array1[i] == 0:
    l.append(i)
print(l)

[2, 6]


In [26]:
print(np.where(np.array(array1)==0))

(array([2, 6], dtype=int64),)


### Remove columns containing missing values

In [47]:
array1 =[[2,np.nan,1,12,5],
         [6,np.nan,7,8,19],
         [3,np.nan,5,4,6]]

index = np.isnan(array1).any(axis=0)
array1 = np.delete(array1, index,axis=1)
array1

array([[ 2.,  1., 12.,  5.],
       [ 6.,  7.,  8., 19.],
       [ 3.,  5.,  4.,  6.]])

### All the negative values to zero

In [48]:
import numpy as np
array1= [2,3,-4,2,-2,-7,7]

for i in range(len(array1)):
  if array1[i]<0:
    array1[i] = 0
print(array1)

[2, 3, 0, 2, 0, 0, 7]


### Replace the missing value with average

In [49]:
# array1= [[11, 14, 51, np.nan],
#          [17, 41, np.nan, 19],
#          [np.nan, 16, 15, 81]]
# np.take(np.nanmean(array1), np.isnan(array1).any(axis=1))

In [54]:
a = ['a','b','c','d']
n = len(a)
for i in range(int(len(a)/2)):
    a[i] , a[n-i-1] = a[n-i-1],a[i]
"".join(a)

'dcba'

In [58]:
import numpy as np

print(np.linalg.det(A))

-144.0


In [1]:
from scipy import linalg

print(linalg.norm(A@B))

NameError: name 'A' is not defined

In [62]:
num = sum(list1 )
factorial = 1    
if num < 0:    
   print(" Factorial does not exist for negative numbers")    
elif num == 0:    
   print("The factorial of 0 is 1")    
else:    
   for i in range(1,num + 1):    
       factorial = factorial*i    
   print(factorial)   

120


In [78]:
#Importing NumPy Library
import numpy as np
from numpy.ndarray import 
list1= [1, 2, 3, 4, 5, 6]
n = len(list1)
for i in range(int(n/2)):
        list1[i],list1[n-i-1]=list1[n-i-1],list1[i] 
print(list1)

[6, 5, 4, 3, 2, 1]


In [ ]:
import scipy
from scipy.constants import pi
N = 12
def circular_area(N):
  print(pi*(N/2)**2)
circular_area(N)

In [81]:
from numpy import ndarray 
print(np.array(array1).flatten())

[2 3 0 2 0 0 7]


### missing values with average

In [96]:
# import numpy as np
# array1= [[11, 14, 51, np.nan],
#          [17, 41, np.nan, 19],
#          [np.nan, 16, 15, 81]]
# indeces = []
# for i in range(len(array1)):
#     for j in range(len(array1[i])):
#         if type(array1[i][j]) == type(np.nan):
#             indeces.append([i,j])
# indeces

In [127]:
array1= [[2, 4, 5, np.nan],
         [7, 4, np.nan, 9],
         [np.nan, 6, 5, 8]]
array1 = np.array(array1) 
averages = np.nanmean(array1, axis=0)
averages

array([4.5       , 4.66666667, 5.        , 8.5       ])

In [128]:
missing_indices = np.isnan(array1)
missing_indices

array([[False, False, False,  True],
       [False, False,  True, False],
       [ True, False, False, False]])

In [129]:
row_indices, col_indices = np.where(missing_indices)
np.where(missing_indices)

(array([0, 1, 2], dtype=int64), array([3, 2, 0], dtype=int64))

In [130]:
np.array(averages)[col_indices]

array([8.5, 5. , 4.5])

In [131]:
array1[row_indices, col_indices] = np.array(averages)[col_indices]
array1

array([[2. , 4. , 5. , 8.5],
       [7. , 4. , 5. , 9. ],
       [4.5, 6. , 5. , 8. ]])

In [138]:
from sklearn.impute import SimpleImputer
import numpy as np
array1= [[2, 4, 5, np.nan],
         [7, 4, np.nan, 9],
         [np.nan, 6, 5, 8]]
array1 = np.array(array1) 
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(array1)
imputer.transform(array1)

array([[2. , 4. , 5. , 8.5],
       [7. , 4. , 5. , 9. ],
       [4.5, 6. , 5. , 8. ]])

### eigan vectors

In [141]:
from numpy.linalg import eig
array1 =[[1, 1, 4],
         [1, 2, 4],
         [1, 3, 1]]
print(eig(array1))

(array([ 5.93632273,  0.23296302, -2.16928575]), array([[-0.54902799, -0.95101849, -0.64593923],
       [-0.66025005,  0.28884154, -0.44212699],
       [-0.51248232,  0.1101562 ,  0.62232325]]))


### Stack two arrays index by index

In [152]:
array1 = ([1,2,3])
array2 = ([4,5,6])
np.stack((array1,array2),axis = 1)

array([[1, 4],
       [2, 5],
       [3, 6]])

In [153]:
from numpy import array
combined_array = [[x, y] for x, y in zip(array1, array2)]
print(array(combined_array))

[[1 4]
 [2 5]
 [3 6]]


### Difference between vector norm and condition number

In [159]:
matrix1 = [[1, 2],[3, 7]]
np.linalg.norm(matrix1) - np.linalg.cond(matrix1)

-55.0468690496682

In [167]:
point_1 = (10,12,20)
point_2 = (13,11,2)

In [168]:
import math
def euc(point_1,point_2):
    dis = math.sqrt((point_2[0]-point1[1])

SyntaxError: unexpected EOF while parsing (3248075525.py, line 3)

### euclidian distance

In [173]:
import math
math.sqrt((point_2[0]-point_1[0])**2 +(point_2[1]-point_1[1])**2 + (point_2[2]-point_1[2])**2)

18.275666882497067

### Harmonic mean

In [180]:
import numpy as np
import statistics
data1 = [100,120,122,123,143,159]

def harmonicmean(data1):
    n = len(data1)
    dev = 0
    for i in range(n):
        dev = dev + (1 /(data1[i]))
    print(n/dev)
harmonicmean(data1)

0.047942451114729376


In [183]:
data1 = [100,120,122,123,143,159]
len(data1)/(1/100 + 1/120 + 1/122 + 1/123 + 1 / 143 + 1/159)

125.15004678508433

### harmonicmean

In [187]:
def harmonicmean(data1):
    n = len(data1)
    dev = 0
    for i in range(n):
        dev = dev + (1 /(data1[i]))
    print(n/dev)
harmonicmean(data1)

125.15004678508433


### mean

In [188]:
sum(data1)/len(data1)

127.83333333333333

### Calculate the Median

In [227]:
import statistics
print(statistics.median(data1))

95.0


### Calculate the Mode

In [271]:
data1 = [45,46,47,48,46]

d = {}
for i in data1:
    if i not in d:
        d[i] = 0
    if i in d:
        d[i] += 1
# set(d)

d

{45: 1, 46: 2, 47: 1, 48: 1}

In [274]:
max_freq = 0
modes = 0
for key, value in d.items():
    if value > max_freq:
        max_freq = value
        modes = key
    elif value == max_freq:
        modes = key
modes

46

### Median of a grouped continuous data

In [275]:
print(statistics.median_grouped(data1))

46.25


###  The high median

In [277]:
array1 = [1,2,3,4]

print(statistics.median_high(array1))

3


###  The low median

In [309]:
array1 = [1,2,3,4]
print(statistics.median_low(array1))

2


### Standard deviation of a population

In [310]:
from fractions import Fraction as fr
P1 = [15,33,34,16,37,18,20]
print(statistics.stdev(P1))

9.516902257112267


In [311]:
import math
def calculate_standard_deviation(population):
    n = len(population)
    mean = sum(population) / n

    squared_diff_sum = sum((x - mean) ** 2 for x in population)

    standard_deviation = math.sqrt(squared_diff_sum / n)
    return standard_deviation
result = calculate_standard_deviation(P1)
print(result)

8.8109393972053


### sum of concated array

In [312]:
array1 = [1, 1, 1]
array2 = [1, 1, 1]
print(sum(array1 +array2))

6


### remove or pop element from list

In [313]:
array1 = [90,20,30,11]
K = 2
array1.pop(K)

30

In [314]:
array1

[90, 20, 11]

### Population variance

In [315]:
import statistics
print(statistics.pvariance(data1))

1.04


### Sample variance

In [316]:
print(statistics.variance(data1))

1.3


### The N-th quantile

In [317]:
array1 = [39,5,31,43,48,50,41,7,11,15,31]
N = 75

In [323]:
print(np.quantile(array1,N/100))

42.0


###  The N-th percentile

In [365]:
array1 = [32, 36, 46, 47, 56, 69, 75, 79, 79, 88, 89, 91, 92, 93, 96, 97]
N = 50

print(np.percentile(array1,50))

79.0


In [449]:
import math

def calculate_percentile(array, N):
    sorted_array = sorted(array)
    index = (N / 100) * (len(sorted_array) - 1)
    floor_index = math.floor(index)
    ceil_index = math.ceil(index)
    
    if floor_index == ceil_index:
        return sorted_array[int(index)]
    
    lower_value = sorted_array[int(floor_index)] * (ceil_index - index)
    upper_value = sorted_array[int(ceil_index)] * (index - floor_index)
    
    return lower_value + upper_value

result = calculate_percentile(array1, N)
print(result)

53.75


### Row-wise addition in tuple matrix

In [450]:
A = [[("a","b")],[("d","e")]]
B = ["c","f"]
l = []
for i,j in enumerate(A):
    l.append(list(j[0]))
    l[i].append(B[i])
print([tuple(inner_list) for inner_list in l])

[('a', 'b', 'c'), ('d', 'e', 'f')]


In [451]:
l = []
for i,j in enumerate(A):
    l.append(list(j[0]))
    l[i].append(B[i])
print([[tuple(inner_list) for inner_list in l]])

[[('a', 'b', 'c'), ('d', 'e', 'f')]]


In [452]:
l = []
for i,j in enumerate(A):
    l.append(list(j[0]))
    l[i].append(B[i])
[tuple(inner_list) for inner_list in l]

[('a', 'b', 'c'), ('d', 'e', 'f')]

In [453]:
# for i in range(len(l)):
#     print(l[i].append(B[i]))
l

[['a', 'b', 'c'], ['d', 'e', 'f']]

In [454]:
l

[['a', 'b', 'c'], ['d', 'e', 'f']]

### reverse of nth array

In [455]:
A = [[ 11, 12, 13 ], [12, 22, 33 ], [ 21, 32, 43 ]]
N = 3

def reverse(l):
    return l[::-1]

def row_reversion(matrix,N):
    for i in range(len(matrix)):
        if N == i:
            matrix[i] = matrix[i][::-1]
            print(matrix)
            break
row_reversion(A,N-1)

[[11, 12, 13], [12, 22, 33], [43, 32, 21]]


In [456]:
for i in range(len(A)):
  if N-1 == i:
    A[i] = A[i][::-1]
    print(A)

[[11, 12, 13], [12, 22, 33], [21, 32, 43]]


### Armstrong Number

In [457]:
N = 153
def ArmstrongNumber(N):
    strr = str(N)
    summ = 0
    for i in strr:
        summ += int(i) ** len(strr)
    if str(summ)==strr:
        print('Yes')
    else:
        print('No')
ArmstrongNumber(N)

Yes


In [458]:
ArmstrongNumber(15)

No


### Interquartile range

In [461]:
from scipy import stats
data1= [32, 36, 46, 47, 56, 69, 75, 96, 97]

IQR = stats.iqr(data1, interpolation = 'midpoint')
  
print(IQR)

29.0


In [463]:
import math
data1.sort()
def calculate_percentile(array, N):
    sorted_array = sorted(array)
    index = (N / 100) * (len(sorted_array) - 1)
    floor_index = math.floor(index)
    ceil_index = math.ceil(index)
    
    if floor_index == ceil_index:
        return sorted_array[int(index)]
    
    lower_value = sorted_array[int(floor_index)] * (ceil_index - index)
    upper_value = sorted_array[int(ceil_index)] * (index - floor_index)
    
    return lower_value + upper_value

q1 = calculate_percentile(data1, 25)
q3 = calculate_percentile(data1, 75)

iqr = q3 - q1
print(float(iqr))

29.0


In [465]:
#Write the code 
coupon = [625, 40081787109376, 821289025, 1, 5, 6, 25, 76, 376, 376, 625, 9376,]

w = 0
for i in coupon :
  if i%5 == 0:
    w+=1
  else:
    pass
print(w)

5


### Salary prediction

In [488]:
from sklearn.linear_model import LinearRegression
# def salary_prediction(X_train,X_test,y_train):
X_train =[[1],[2],[3],[4],[5],[6]]
X_test = [[7]]
y_train =[1000,2000,3000,4000,5000,6000]
model = LinearRegression()
model.fit(X_train,y_train)
model.predict(X_test)

array([7000.])

### Weight prediction using Bayesian regression

In [487]:
from sklearn.linear_model import BayesianRidge
X_train =[[5.9,9000,23],[6,7000,22],[5.5,6700,23],[6.4,6500,24],[5.6,5000,23]]
X_test = [[5.9,7000,24]]
y_train =[52,65,64,63,80]
BayesianRidge().fit(X=X_train,y=y_train).predict(X_test)

array([63.75359204])

In [493]:
A = [[5, 15, 9],
     [2, 33, 3],
     [11, 4, 22]]
from numpy.linalg import eig
val , _ = eig(A)
print(eig(A)[0])

[ 0.24847566 22.99041797 36.76110637]


### ROC AUC

In [494]:
from sklearn.metrics import roc_auc_score
y_true = [0,1,1,1,1,1,0,1,0,1]
y_pred = [0,1,0,0,1,0,1,0,0,1]
roc_auc_score(y_true, y_pred)

0.5476190476190477

### Update the last column of a matrix

In [519]:
A = [[15, 21, 34, 42],
     [55, 60, 70, 45],
     [43, 44, 62, 12]]

B = [[12, 22, 32, 42], 
     [33, 33, 44, 55], 
     [90, 95, 17, 87]]

In [522]:
A = [[15, 21, 34, 42],
     [55, 60, 70, 45],
     [43, 44, 62, 12]]

B = [[12, 22, 32, 42], 
     [33, 33, 44, 55], 
     [90, 95, 17, 87]]
print("Matrix A Before = ",A)
print("Matrix B Before = ",B)

for i in range(len(A)):
    for j in range(len(A[i])):
        if A[i][j] == A[i][-1]:
            B[i][j]=A[i][j]

print("Matrix A After = ",A)
print("Matrix B After = ",B)

Matrix A Before =  [[15, 21, 34, 42], [55, 60, 70, 45], [43, 44, 62, 12]]
Matrix B Before =  [[12, 22, 32, 42], [33, 33, 44, 55], [90, 95, 17, 87]]
Matrix A After =  [[15, 21, 34, 42], [55, 60, 70, 45], [43, 44, 62, 12]]
Matrix B After =  [[12, 22, 32, 42], [33, 33, 44, 45], [90, 95, 17, 12]]


In [516]:
A

[[15, 21, 34, 42], [55, 60, 70, 45], [43, 44, 62, 12]]

### Words in a string based on the length

In [536]:
string1 = "12 123 1234 12345"
#  [['ab', 'abcd', 'abcdef'], ['a', 'abc', 'abcde']]
string1 = string1.split(' ')
l = [[],[]]
for i in string1:
    n = len(i)
    if n%2==0:
        l[0].append(i)
    else:
        l[1].append(i)
print(l)

[['12', '1234'], ['123', '12345']]


In [535]:
l

[['ab', 'abcd', 'abcdef'], ['a', 'abc', 'abcde']]

### Split a list into evenly sized buckets

In [537]:
list1 = [1,2,3,4,5,6]
B = 3
# [[1, 2, 3], [4, 5, 6]]

In [544]:
list((list1[:B] , list1[B:]))

[[1, 2, 3], [4, 5, 6]]

In [5]:
list1 = [2,2,3,4,5,5,5,6,7,8,8,8,8,8,9,9,10,11,11,12]
len(list1)

20

In [6]:
list1.index(10)

16

### persentile

In [28]:
def persentile(x,l):
    l.sort()
    return (l.index(x)/len(l))*100

In [29]:
persentile(5,list1)

20.0

### what value exist at rank 25

In [30]:
def rank(pv,l):
    return (pv/ 100 ) * (len(l)+1)

In [31]:
rank(25,list1)

5.25

In [38]:
 rank(75,list1) - rank(25,list1) 

10.5

### treating outliers
- boxplot is best way to find out liers

In [80]:
,

(3, 8)

In [6]:
data1 = [-122,29,27,25,26,29,28,90,22.2,19.09]
def rank(pv,l):
    return (pv/ 100 ) * (len(l)+1)

Q1 = data1[int(rank(25,data1))]
Q3 = data1[int(rank(75,data1))]
IQR = Q3-Q1
upper_fence = Q3 + (1.5 * IQR)
lower_fence = Q1 - (1.5 * IQR)
upper_fence,lower_fence

(14.999999999999998, 34.2)

In [133]:
upper_fence

14.999999999999998

In [9]:
import numpy as np

def rank(pv, l):
    return (pv / 100) * (len(l) + 1)

data1 = [1, 2, 3, 4, 5, 6, -12, 28]

Q1 = np.percentile(data1, 25)
Q3 = np.percentile(data1, 75)
IQR = Q3 - Q1
upper_fence = Q3 + (1.5 * IQR)
lower_fence = Q1 - (1.5 * IQR)

outliers = []
for i in data1:
    if i < lower_fence or i > upper_fence:
        outliers.append(i)

print(outliers)

[-12, 28]


### Standard skewness estimator
### Skewness estimator based on quartiles

In [25]:
data1 = [19,33,17,69,23,12]

from statsmodels.stats.stattools import robust_skewness
print(robust_skewness(data1))

(1.3743538608029828, 0.46153846153846156, 0.6103896103896103, 0.41049991941918956)


### Skewness estimator standardized by absolute deviation

In [42]:
data1 = [19,33,17,69,23,12]
import numpy as np
((sum(data1) / len(data1)) - data1[int(len(data1)/2)]) /  np.std(data1)

-2.104903842128185

### Difference between the maximum and minimum elements in a set

In [12]:
set1 = {1,2,3,4,5,6}
print(max(set1)-min(set1))

5


In [45]:
from statsmodels.stats.stattools import robust_skewness

def skewness_estimator(data):
    skewness = robust_skewness(data)
    return skewness

# Example 1
data1 = [5, 31, 43, 48, 50, 41, 71, 15, 3, 8, 6, 25, 36, 27, 61, 31]
skewness1 = skewness_estimator(data1)
print(skewness1)

# Example 2
data2 = [19, 33, 17, 69, 23, 12]
skewness2 = skewness_estimator(data2)
print(skewness2)


(0.22177556874606705, -0.14516129032258066, 0.019157088122605363, 0.01569945769043999)
(1.3743538608029828, 0.46153846153846156, 0.6103896103896103, 0.41049991941918956)


### Standard kurtosis estimator

In [51]:
import numpy as np
from statsmodels.stats.stattools import robust_kurtosis
print(robust_kurtosis(np.array(data1))[0])

5.666483687975743


###  Kurtosis estimator based on octiles

In [53]:
data1 = [93,6,97,101,25,316,225,36,27,61,31]
print(robust_kurtosis(np.array(data1))[1])

0.3276191702290685


### Kurtosis estimators based on exceedance expectations

In [59]:
data1 = [19,33,17,692,23,12]
print(robust_kurtosis(np.array(data1))[2])

0.32905859141491156


### Kurtosis measure based on the spread between high and low quantiles

In [60]:
data1 = [19,33,17,692,23,12]
print(robust_kurtosis(np.array(data1))[-1])

43.017229971406756


### Jarque-Bera test statistic value

In [61]:
from statsmodels.stats.stattools import jarque_bera
data1 = [5,31,43,48,50,41,71,15,3,8,6,25,36,27,61,31]
jarque_bera(data1)[0]

(0.6194500551071879,
 0.7336486616585988,
 0.22177556874606705,
 2.144174392127569)

### p-value of the Jarque-Bera test statistic

In [64]:
data1 = [19,33,173,69,23,12,5,31,43,48,50]
jarque_bera(data1)[1]

0.0012054256385713618

### Skewness and kurtosis by the Jarque-Bera normality test

In [68]:
data1 = [930,33,217,629,23,112,5,321,43,812,250]
jarque_bera(data1)[-2],jarque_bera(data1)[-1]

(0.8666431666254093, 2.250818348586192)

### Chi-square using the omnibus test for normality

In [70]:
data1 = [930,33,217,629,23,112,5,321,43,812,250]
from statsmodels.stats.stattools import omni_normtest
omni_normtest(data1)[0]

2.4089084273901746

### Two-tailed probability using the omnibus test for normality

In [71]:
data1 = [930,33,217,629,23,112,5,321,43,812,250]
from statsmodels.stats.stattools import omni_normtest
omni_normtest(data1)[1]

0.299855611946924

### Medcouple measure of skewness

In [73]:
from statsmodels.stats.stattools import medcouple
data1 = [88, 893, 91, 932, 93, 96, 97,101]
print(medcouple(data1))

0.8894409937888199


### Durbin-Waston statistic

In [74]:
data1 = [88, 893, 91, 932, 93, 96, 97,101]
from statsmodels.stats.stattools import durbin_watson
durbin_watson(data1)

1.5715860856154407

### Descriptive statistics

In [76]:
from scipy.stats import describe
data1=[1121.0,1151.00,1121.00,1134.0,1135.60,10161.0,1157.18,1146.8,1149.00,1128.75,1135.0,1134.60]
describe(data1)

DescribeResult(nobs=12, minmax=(1121.0, 10161.0), mean=1889.5775, variance=6785231.39389318, skewness=3.0150087719269654, kurtosis=7.0905303143822955)

### Geometric average

In [77]:
data1 = [5,31,43,48,50,41,71,15,3,8,6,25,36,27,61,31]
from scipy.stats.mstats import gmean

In [78]:
gmean(data1)

22.596975885754418

### nth moment

In [81]:
from scipy.stats import moment
data1= [5,9,45,78,4,3,2,5,7,92,11]
N = 3
print(moment(data1,N))

39800.7362885049


### The nth k-statistics

In [141]:
from scipy.stats import kstat
print(kstat(data1))

9.166666666666666


### Variance of the k-statistics

In [142]:
from scipy.stats import kstat
data1 = [88,893,91,932,93,96,97,101]
print(kstat(data1))

143566.125


### Trimmed mean

In [175]:
from scipy.stats import trim_mean
data1 = [5,31,43,48,57,61,31]
trim_mean(data1,proportiontocut=.0)

39.42857142857143

### Trimmed variance

In [178]:
from scipy.stats import mstats
data1 = [1,62,9,10,25,31,23,36,27,61,31]

mstats.trimmed_var(data1, ddof=0)

210.09876543209873

### Trimmed minimum

In [186]:
from scipy.stats import mstats
data1 = [11,62,9,10,25,31,23,36,27,61,31]
L=19

print(mstats.tmin(data1,L))

23


### Trimmed maximum

In [210]:
from scipy.stats.mstats import tmax
data1 = [11,62,9,10,25,31,23,36,27,61,31]
L=19

print(mstats.tmax(data1,L))

11


### Trimmed sample standard deviation

In [211]:
from scipy.stats.mstats import trimmed_std
data1 = [931,62,97,101,25,316,23425,36,27,61,31]

print(trimmed_std(data1))

276.85977196648366


### Trimmed sample standard deviation

In [212]:
from scipy import stats
print(stats.tstd(data1))

7017.119173201285


### Coefficient of variation

In [217]:
from scipy.stats import variation
data1 = [88,93,1,43,48,50,41,91,932,93,96,97,101]

print(variation(data1))

1.6968455353998737


### Geometric standard deviation

In [218]:
from scipy.stats import gstd

data1 = [5,31,43,48,50,41,71,15,3,8,6,25,36,27,61,31]

print(gstd(data1))

2.6348853951512816


### Standard error of the mean

In [219]:
from scipy.stats import sem
sem(data1)

5.139486639409297

###  Entropy of a distribution

In [220]:
dist1 = [1/6, 1/6, 1/6, 1/6, 1/6, 1/6]
from scipy.stats import entropy
entropy(dist1)

1.791759469228055

### Differential entropy of a distribution

In [221]:
sample1 = [0.009, 0.11, 0.002, 0.032, 0.047]
from scipy.stats import differential_entropy
print(differential_entropy(sample1))

-1.8259244896227593


###  Repeats and repeat count

In [242]:
array1 = [1,2,3,4,5,3,3,5]
from scipy.stats import find_repeats
find_repeats(array1)

RepeatedResults(values=array([3., 5.]), counts=array([3, 2], dtype=int64))

### Cumulative frequency

In [243]:
array1 = [1,2,3,4,5,3,3,5]
from scipy.stats import cumfreq
print(cumfreq(array1)[0])

[1. 1. 2. 2. 2. 5. 5. 6. 6. 8.]


### Score at a given percentile

In [244]:
array1 = [930,33,217,629,23,112,5,321,43,812,250]
P =50
from scipy.stats import scoreatpercentile
scoreatpercentile(array1,P)

217.0

### One-Way ANOVA test for binary population groups

In [247]:
from scipy.stats import f_oneway
p1=[6,2,3,4,2,3,3,2,7,8,10,4]
p2=[4,4,5,7,8,5,3,7,10,4,5,2]
print(f_oneway(p1,p2))

F_onewayResult(statistic=0.685785536159601, pvalue=0.4164952236988999)


### One-Way ANOVA test for multiple population groups

In [248]:
from scipy.stats import f_oneway
p1=[6,2,3,4,2,3,3,2,7,8,10,4]
p2=[4,4,5,7,8,5,3,7,10,4,5,2]
p3=[5,31,43,48,50,41,71,15,3,8,6,25,36,27,61,31]
p4=[919,393,173,69,23,12,5,31,43,48,50]
print(f_oneway(p1,p2,p3,p4))

F_onewayResult(statistic=3.8556534687126023, pvalue=0.015117004708209373)


### T-test for two independent samples

In [249]:
p1=[6,2,3,4,2,3,3,2,7,8,10,4]
p2=[4,4,5,7,8,5,3,7,10,4,5,2]

from scipy.stats import ttest_ind
print(ttest_ind(p1,p2))

Ttest_indResult(statistic=-0.828121691636924, pvalue=0.4164952236988998)


### Normality test

In [252]:
from scipy.stats import normaltest
p1=[31,62,97,101,25,16,25,36,27,61,31]

normaltest(p1)

C:\Users\vivek codes\anaconda3\lib\site-packages\scipy\stats\_stats_py.py:1769: UserWarning: kurtosistest only valid for n>=20 ... continuing anyway, n=11
  warnings.warn("kurtosistest only valid for n>=20 ... continuing "


NormaltestResult(statistic=2.736789623110956, pvalue=0.254515176652981)

### Kurtosis test

In [254]:
from scipy.stats import kurtosistest
data1=[31,62,97,101,25,16,25,36,27,61,31]

print(kurtosistest(data1))

KurtosistestResult(statistic=0.07891052215476219, pvalue=0.9371037938728526)


### Test of skewness

In [256]:
data1=[6,2,3,4,2,3,3,2,7,8,10,4]

from scipy.stats import skewtest
print(skewtest(data1))

SkewtestResult(statistic=1.5935343886099593, pvalue=0.11104036012028762)


### Mood’s two-sample test for equal scale parameters 

In [2]:
from scipy.stats import mood,median_test

In [4]:
from scipy.stats import mood,median_test
mood(sample1,sample2)

(-1.7309620502960825, 0.08345853325870158)

### Mood’s median test

In [6]:
from scipy.stats import mood,median_test
print(median_test(sample1,sample2))

(4.583333333333334, 0.03228435391076682, 6.5, array([[3, 8],
       [9, 2]], dtype=int64))


### One-way chi-square test

In [10]:
F_ob=[1, 18, 6, 4, 12, 12]
F_exp=[1, 16, 6, 6, 16, 8]

In [11]:
from scipy.stats import chisquare
print(chisquare(f_obs=F_ob, f_exp=F_exp))

Power_divergenceResult(statistic=3.9166666666666665, pvalue=0.5614753252040727)


### T-test on two related samples

In [13]:
sample1 =[30,68,77,119,35,11,33,30,29,62,39]
sample2=[31,62,97,101,25,16,25,36,27,61,31]
from scipy.stats import ttest_rel
print(ttest_rel(sample1,sample2))

Ttest_relResult(statistic=0.6285059317130549, pvalue=0.5437600392053596)


### z-score

In [15]:
from scipy.stats import zscore
print(zscore(sample1))

[-0.63370699  0.6711675   0.98021672  2.42244642 -0.46201298 -1.28614423
 -0.53069058 -0.63370699 -0.66804579  0.46513469 -0.32465777]


### Covariance matrix for binary variables

In [17]:
data1= [19,18,17,16,15]
data2= [21,22,23,24,25]
import numpy as np
np.cov(data1,data2)

array([[ 2.5, -2.5],
       [-2.5,  2.5]])

### Pearson’s correlation coefficient

In [18]:
data1 = [10, 2, 30, 4, 5, 60, 7, 8, 9]
data2 = [9, 80, 7, 6, 50, 4, 3, 20, 1]

In [19]:
from scipy.stats import pearsonr 
print(pearsonr(data1,data2))

PearsonRResult(statistic=-0.3772226833407402, pvalue=0.3169193867578748)


### Spearman’s correlation coefficient

In [22]:
from scipy.stats import spearmanr;
print(spearmanr(data1,data2))

SpearmanrResult(correlation=-0.43333333333333335, pvalue=0.2439524358800516)


### Alexander-Govern test

In [23]:
from scipy.stats import alexandergovern
print(alexandergovern(data1,data2))

AlexanderGovernResult(statistic=0.19287640464766484, pvalue=0.6605333161665234)


### Correlation measure for ordinal data

In [26]:
data1 = [10, 2, 30, 4, 5, 60, 7, 8, 9]
data2 = [9, 80, 7, 6, 50, 4, 3, 20, 1]

from scipy.stats import kendalltau;
print(kendalltau(data1,data2))

KendalltauResult(correlation=-0.3888888888888889, pvalue=0.18018077601410934)


### Somer’s D for two ordinal association

In [31]:
data1 = [10, 2, 30, 4,9]
data2 = [9, 80, 7, 6, 1]

In [32]:
from scipy.stats import somersd
print(somersd(data1,data2))

SomersDResult(statistic=-0.2, pvalue=0.5761501220305789, table=array([[0, 0, 0, 0, 1],
       [0, 1, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 1, 0, 0]]))


### T-test for the mean of one group of scores

In [33]:
array1 = [10, 2, 30, 4,9]
N = 3
from scipy.stats import ttest_1samp
ttest_1samp(array1,N)

Ttest_1sampResult(statistic=1.6064386578049978, pvalue=0.1834526400556382)

### Standard error of the trimmed mean

In [38]:
array1 = [513,322,373,642,536,675,74,438,529,180]

from scipy.stats.mstats import trimmed_std
print(trimmed_std(array1, (0.1,0.1)))

136.5951476993235


### Probability of drawn colored balls

In [7]:
N1,N2,N3 = 2,3,2

In [8]:
(7/12)*(6/11)

0.3181818181818182

In [9]:
total = N1+N2+N3
print(((N1+N2)/total)*((N1+N2-1)/(total-1)))

0.47619047619047616


### Mood’s two-sample test for equal scale parameters

In [38]:
from scipy.stats.mstats import trimtail;
array1 = [1,2,3,4,5,6,7,8,9,10]
print(trimtail(array1,tail='left',inclusive=(0.50,0.3)))
trimtail(array1,tail='left')

[-- -- 3 4 5 6 7 8 9 10]


masked_array(data=[--, --, 3, 4, 5, 6, 7, 8, 9, 10],
             mask=[ True,  True, False, False, False, False, False, False,
                   False, False],
       fill_value=999999)